name: Install Node.js with PNPM

inputs:
  version:
    description: The Node.js version to install
    required: true
    default: "18.x"
  dependencies:
    description: whether to install dependencies on the root folder
    required: true
    default: "false"
  cache:
    description: Whether installed dependencies should be cached
    required: true
    default: "true"
  pnpm-version:
    description: The PNPM version to install
    required: false
    default: "9.1"

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ fromJson(inputs.pnpm-version) }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.version }}
        cache: "pnpm"

    - name: Install Node.js dependencies
      if: inputs.dependencies == 'true'
      uses: tensor-foundation/actions/install-node-dependencies@v2
      with:
        cache: ${{ inputs.cache }}
        key: "node"
